/* ============================================================
   ALFA SUPLEMENTOS V8 — PAINEL: ANALYTICS + CAMPANHAS
   ============================================================ */
(()=>{
'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const load=()=>window.AlfaStore.load(), save=d=>{window.AlfaStore.save(d);window.AlfaCloud?.schedulePush?.(d)};
const money=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg){const t=$('#adminToast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function injectNav(){const nav=$('.sidebar nav');if(!nav||$('[data-tab="campaigns"]'))return;const btn=document.createElement('button');btn.dataset.tab='campaigns';btn.innerHTML='<i class="fa-solid fa-bullhorn"></i><span>Campanhas V8</span><b class="v8-new">NOVO</b>';const settings=$('[data-tab="settings"]',nav);nav.insertBefore(btn,settings);btn.addEventListener('click',()=>activate('campaigns'))}
function injectTab(){const main=$('.main');if(!main||$('#tab-campaigns'))return;const sec=document.createElement('section');sec.className='tab';sec.id='tab-campaigns';sec.innerHTML=`<div class="v8-admin-hero"><div><span>ALFA CAMPAIGNS</span><h2>Campanhas inteligentes</h2><p>Crie chamadas com período de ativação, dias da semana e destino no site.</p></div><button class="primary" id="v8NewCampaign"><i class="fa-solid fa-plus"></i> Nova campanha</button></div><div class="panel"><div class="panel-head"><div><span>PROGRAMAÇÃO</span><h2>Campanhas cadastradas</h2></div></div><div id="v8CampaignAdminList" class="v8-admin-campaign-list"></div></div>`;const backup=$('#tab-backup');main.insertBefore(sec,backup);$('#v8NewCampaign').onclick=()=>editCampaign();renderCampaigns()}
function activate(name){$$('.tab').forEach(t=>t.classList.toggle('active',t.id===`tab-${name}`));$$('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if($('#pageTitle'))$('#pageTitle').textContent=name==='campaigns'?'Campanhas V8':$('#pageTitle').textContent;if(name==='campaigns')renderCampaigns()}
function campaignActive(c){const n=new Date(),d=n.getDay();if(!c.active)return false;if(c.weekdays?.length&&!c.weekdays.map(Number).includes(d))return false;if(c.startAt&&n<new Date(c.startAt))return false;if(c.endAt&&n>new Date(c.endAt))return false;return true}
function renderCampaigns(){const host=$('#v8CampaignAdminList');if(!host)return;const data=load(),list=data.campaigns||[];host.innerHTML=list.length?list.map(c=>`<article><div class="v8-campaign-state ${campaignActive(c)?'on':'off'}"><i></i>${campaignActive(c)?'ATIVA AGORA':'INATIVA'}</div><div><small>${esc(c.tag||'CAMPANHA')}</small><h3>${esc(c.title)}</h3><p>${esc(c.subtitle||'')}</p><span>${c.startAt?new Date(c.startAt).toLocaleString('pt-BR'):'Sempre'} → ${c.endAt?new Date(c.endAt).toLocaleString('pt-BR'):'Sem término'}</span></div><div class="v8-campaign-actions"><button data-edit-campaign="${esc(c.id)}"><i class="fa-solid fa-pen"></i></button><button data-toggle-campaign="${esc(c.id)}"><i class="fa-solid fa-power-off"></i></button><button data-delete-campaign="${esc(c.id)}"><i class="fa-solid fa-trash"></i></button></div></article>`).join(''):'<div class="empty">Nenhuma campanha cadastrada.</div>';$$('[data-edit-campaign]',host).forEach(b=>b.onclick=()=>editCampaign(b.dataset.editCampaign));$$('[data-toggle-campaign]',host).forEach(b=>b.onclick=()=>{const d=load(),c=d.campaigns.find(x=>x.id===b.dataset.toggleCampaign);if(c){c.active=!c.active;save(d);renderCampaigns();toast('Status da campanha alterado')}});$$('[data-delete-campaign]',host).forEach(b=>b.onclick=()=>{if(!confirm('Excluir esta campanha?'))return;const d=load();d.campaigns=d.campaigns.filter(x=>x.id!==b.dataset.deleteCampaign);save(d);renderCampaigns();toast('Campanha excluída')})}
function editCampaign(id){const d=load(),old=(d.campaigns||[]).find(x=>x.id===id)||{id:`camp-${Date.now()}`,title:'',subtitle:'',tag:'OFERTA ALFA',cta:'VER AGORA',target:'#produtos',theme:'orange',active:true,weekdays:[0,1,2,3,4,5,6],startAt:null,endAt:null};const body=$('#modalBody');if(!body)return;const dt=v=>v?String(v).slice(0,16):'';body.innerHTML=`<div class="modal-head"><span>V8 CAMPAIGNS</span><h2>${id?'Editar':'Nova'} campanha</h2></div><form id="v8CampaignForm" class="modal-form"><label class="full">Título<input id="v8cTitle" value="${esc(old.title)}" required></label><label class="full">Subtítulo<textarea id="v8cSubtitle">${esc(old.subtitle)}</textarea></label><label>Tag<input id="v8cTag" value="${esc(old.tag)}"></label><label>CTA<input id="v8cCta" value="${esc(old.cta)}"></label><label>Destino<input id="v8cTarget" value="${esc(old.target)}"></label><label>Tema<select id="v8cTheme"><option value="orange">Laranja</option><option value="graphite">Grafite</option><option value="white">Claro</option></select></label><label>Começa em<input id="v8cStart" type="datetime-local" value="${dt(old.startAt)}"></label><label>Termina em<input id="v8cEnd" type="datetime-local" value="${dt(old.endAt)}"></label><label class="full v8-days">Dias da semana<div>${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((x,i)=>`<label><input type="checkbox" data-v8-day="${i}" ${old.weekdays?.includes(i)?'checked':''}><span>${x}</span></label>`).join('')}</div></label><label class="switch full"><input id="v8cActive" type="checkbox" ${old.active?'checked':''}><span></span> Campanha ativa</label><button class="primary full">Salvar campanha</button></form>`;$('#v8cTheme').value=old.theme||'orange';$('#adminModal').classList.add('active');$('#v8CampaignForm').onsubmit=e=>{e.preventDefault();const data=load();data.campaigns=data.campaigns||[];const c={...old,title:$('#v8cTitle').value.trim(),subtitle:$('#v8cSubtitle').value.trim(),tag:$('#v8cTag').value.trim(),cta:$('#v8cCta').value.trim(),target:$('#v8cTarget').value.trim()||'#produtos',theme:$('#v8cTheme').value,startAt:$('#v8cStart').value?new Date($('#v8cStart').value).toISOString():null,endAt:$('#v8cEnd').value?new Date($('#v8cEnd').value).toISOString():null,weekdays:$$('[data-v8-day]:checked').map(x=>Number(x.dataset.v8Day)),active:$('#v8cActive').checked};const pos=data.campaigns.findIndex(x=>x.id===c.id);if(pos>=0)data.campaigns[pos]=c;else data.campaigns.push(c);save(data);$('#adminModal').classList.remove('active');renderCampaigns();toast('Campanha salva com sucesso')};}
function analytics(){const dash=$('#tab-dashboard');if(!dash||$('#v8Analytics'))return;const wrap=document.createElement('div');wrap.id='v8Analytics';wrap.className='v8-analytics';wrap.innerHTML=`<article class="panel"><div class="panel-head"><div><span>V8 ANALYTICS</span><h2>Receita dos últimos 7 dias</h2></div><b id="v8WeekRevenue"></b></div><canvas id="v8RevenueChart" height="190"></canvas></article><article class="panel"><div class="panel-head"><div><span>CONVERSÃO</span><h2>Saúde comercial</h2></div></div><div id="v8ConversionMetrics" class="v8-metrics"></div></article>`;dash.appendChild(wrap);paintAnalytics()}
function paintAnalytics(){const d=load(),orders=d.orders||[],now=new Date();const days=[...Array(7)].map((_,i)=>{const x=new Date(now);x.setHours(0,0,0,0);x.setDate(x.getDate()-(6-i));return x});const vals=days.map(day=>orders.filter(o=>{const x=new Date(o.createdAt);return x.toDateString()===day.toDateString()&&o.status!=='cancelled'}).reduce((s,o)=>s+Number(o.total||0),0));$('#v8WeekRevenue').textContent=money(vals.reduce((a,b)=>a+b,0));const canvas=$('#v8RevenueChart');if(canvas){const ctx=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*devicePixelRatio,h=canvas.height=190*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=canvas.clientWidth,H=190,max=Math.max(...vals,1),pad=18;ctx.clearRect(0,0,W,H);ctx.lineWidth=2;ctx.strokeStyle='rgba(255,106,0,.95)';ctx.beginPath();vals.forEach((v,i)=>{const x=pad+i*(W-pad*2)/6,y=H-pad-(v/max)*(H-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();vals.forEach((v,i)=>{const x=pad+i*(W-pad*2)/6,y=H-pad-(v/max)*(H-pad*2);ctx.fillStyle='#ff6a00';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#777';ctx.font='10px Inter';ctx.textAlign='center';ctx.fillText(days[i].toLocaleDateString('pt-BR',{weekday:'short'}),x,H-2)})}const completed=orders.filter(o=>o.status==='completed').length,cancelled=orders.filter(o=>o.status==='cancelled').length,customers=(d.customers||[]).length,ticket=orders.length?orders.reduce((s,o)=>s+Number(o.total||0),0)/orders.length:0;$('#v8ConversionMetrics').innerHTML=`<span><small>PEDIDOS</small><b>${orders.length}</b></span><span><small>CONCLUÍDOS</small><b>${completed}</b></span><span><small>CANCELADOS</small><b>${cancelled}</b></span><span><small>CLIENTES</small><b>${customers}</b></span><span><small>TICKET MÉDIO</small><b>${money(ticket)}</b></span>`}
function settings(){const f=$('#settingsForm');if(!f||$('#setV8Tracking'))return;const b=f.querySelector('button[type=submit]');const html=document.createRange().createContextualFragment(`<div class="full v8-settings-title"><span>V8 • EXPERIÊNCIA DO CLIENTE</span></div><label>Central do cliente<select id="setV8Tracking"><option value="true">Ativada</option><option value="false">Desativada</option></select></label><label>Dock mobile<select id="setV8Dock"><option value="true">Ativado</option><option value="false">Desativado</option></select></label><label>Oferta flutuante<select id="setV8Live"><option value="true">Ativada</option><option value="false">Desativada</option></select></label><label>Duração oferta (min)<input id="setV8OfferMinutes" type="number" min="10" max="1440"></label><label>Rotação campanhas (seg)<input id="setV8CampaignSeconds" type="number" min="3" max="60"></label><label class="full">Texto do rastreamento<input id="setV8TrackHint"></label>`);f.insertBefore(html,b);const d=load().settings||{};$('#setV8Tracking').value=String(d.customerCenterEnabled!==false);$('#setV8Dock').value=String(d.mobileDockEnabled!==false);$('#setV8Live').value=String(d.liveOfferEnabled!==false);$('#setV8OfferMinutes').value=d.liveOfferDurationMinutes||90;$('#setV8CampaignSeconds').value=d.campaignAutoRotateSeconds||7;$('#setV8TrackHint').value=d.customerTrackingHint||'';f.addEventListener('submit',()=>{setTimeout(()=>{const x=load();x.settings.customerCenterEnabled=$('#setV8Tracking').value==='true';x.settings.mobileDockEnabled=$('#setV8Dock').value==='true';x.settings.liveOfferEnabled=$('#setV8Live').value==='true';x.settings.liveOfferDurationMinutes=Number($('#setV8OfferMinutes').value||90);x.settings.campaignAutoRotateSeconds=Number($('#setV8CampaignSeconds').value||7);x.settings.customerTrackingHint=$('#setV8TrackHint').value.trim();save(x)},0)})}
function init(){document.body.classList.add('admin-v8');injectNav();injectTab();analytics();settings();window.addEventListener('alfa:data-updated',paintAnalytics)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,260));else setTimeout(init,260);
})();
