// ALFA SUPLEMENTOS ADMIN V9 — GROWTH, MARGEM, ABC E FIDELIDADE
(()=>{
'use strict';
const $=s=>document.querySelector(s), money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const load=()=>window.AlfaStore.load();
const monthOrders=d=>{const now=new Date();return (d.orders||[]).filter(o=>{const x=new Date(o.createdAt);return x.getMonth()===now.getMonth()&&x.getFullYear()===now.getFullYear()&&o.status!=='cancelled'})};
function productSales(d){const map={};(d.orders||[]).filter(o=>o.status!=='cancelled').forEach(o=>(o.items||[]).forEach(i=>{const id=Number(i.id),qty=Number(i.qty||1),unit=Number(i.unitPrice||0);map[id]??={qty:0,revenue:0};map[id].qty+=qty;map[id].revenue+=qty*unit}));return map}
function paint(){if(!$('#v9GrowthKpis'))return;const d=load(),orders=monthOrders(d),revenue=orders.reduce((s,o)=>s+Number(o.total||0),0),goal=Number(d.settings.monthlyRevenueGoal||12000),sales=productSales(d);let cost=0,gross=0;(d.orders||[]).filter(o=>o.status!=='cancelled').forEach(o=>(o.items||[]).forEach(i=>{const p=(d.products||[]).find(x=>Number(x.id)===Number(i.id));const q=Number(i.qty||1);gross+=Number(i.unitPrice||p?.price||0)*q;cost+=Number(p?.costPrice||0)*q}));const profit=gross-cost,margin=gross?profit/gross*100:0;const customers=d.customers||[],pro=Number(d.settings.loyaltyProThreshold||500),elite=Number(d.settings.loyaltyEliteThreshold||1500),levels={START:0,PRO:0,ELITE:0};customers.forEach(c=>{const t=Number(c.totalSpent||0);levels[t>=elite?'ELITE':t>=pro?'PRO':'START']++});$('#v9GrowthKpis').innerHTML=`<article><small><i class="fa-solid fa-bullseye"></i> RECEITA DO MÊS</small><b>${money(revenue)}</b></article><article><small><i class="fa-solid fa-coins"></i> LUCRO BRUTO EST.</small><b>${money(profit)}</b></article><article><small><i class="fa-solid fa-percent"></i> MARGEM EST.</small><b>${margin.toFixed(1)}%</b></article><article><small><i class="fa-solid fa-crown"></i> CLIENTES ELITE</small><b>${levels.ELITE}</b></article>`;const pct=Math.min(100,goal?revenue/goal*100:0);$('#v9GoalPercent').textContent=`${pct.toFixed(0)}%`;$('#v9GoalBar').style.width=`${pct}%`;$('#v9GoalMeta').innerHTML=`<span>Realizado: <b>${money(revenue)}</b></span><span>Meta: <b>${money(goal)}</b></span><span>Falta: <b>${money(Math.max(0,goal-revenue))}</b></span>`;$('#v9MarginSummary').innerHTML=`<span><small>FATURAMENTO BASE</small><b>${money(gross)}</b></span><span><small>CUSTO ESTIMADO</small><b>${money(cost)}</b></span><span><small>LUCRO BRUTO</small><b>${money(profit)}</b></span>`;const list=(d.products||[]).map(p=>({p,...(sales[p.id]||{qty:0,revenue:0})})).sort((a,b)=>b.revenue-a.revenue),total=list.reduce((s,x)=>s+x.revenue,0);let acc=0;$('#v9AbcTable').innerHTML=list.slice(0,10).map(x=>{acc+=x.revenue;const ratio=total?acc/total:0,cls=ratio<=.8?'A':ratio<=.95?'B':'C';return `<article><em>${cls}</em><span><b>${x.p.name}</b><small>${x.qty} un. • ${money(x.revenue)}</small></span><strong>${total?(x.revenue/total*100).toFixed(1):'0'}%</strong></article>`}).join('')||'<div class="empty">Ainda não há vendas para formar a curva ABC.</div>';$('#v9LoyaltySummary').innerHTML=`<span><small>START</small><b>${levels.START}</b></span><span><small>PRO</small><b>${levels.PRO}</b></span><span><small>ELITE</small><b>${levels.ELITE}</b></span>`;const s=d.settings;$('#v9MonthlyGoal').value=s.monthlyRevenueGoal??12000;$('#v9PointsRate').value=s.loyaltyPointsPerReal??1;$('#v9ProThreshold').value=s.loyaltyProThreshold??500;$('#v9EliteThreshold').value=s.loyaltyEliteThreshold??1500;$('#v9MarginTarget').value=s.defaultMarginTarget??35;$('#v9ReferralReward').value=s.referralRewardPoints??100;}
function setup(){const form=$('#v9GrowthForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const d=load();Object.assign(d.settings,{monthlyRevenueGoal:Number($('#v9MonthlyGoal').value||0),loyaltyPointsPerReal:Number($('#v9PointsRate').value||1),loyaltyProThreshold:Number($('#v9ProThreshold').value||500),loyaltyEliteThreshold:Number($('#v9EliteThreshold').value||1500),defaultMarginTarget:Number($('#v9MarginTarget').value||35),referralRewardPoints:Number($('#v9ReferralReward').value||100)});window.AlfaStore.save(d);paint();if(typeof window.toast==='function')window.toast('Estratégia V9 salva')});document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='growth')setTimeout(paint,50)}));paint()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',setup):setup();
})();
