// ============================================================
// ALFA SUPLEMENTOS V5 — EXPERIÊNCIA INTELIGENTE E CONVERSÃO
// ============================================================
(() => {
  const $ = (s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const getStore = () => window.AlfaStore?.get ? window.AlfaStore.get() : window.ALFA_DEFAULT_DATA;
  const moneyV5 = v => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  const compare = new Set();
  const goalMap = {
    massa: { title:'Stack para ganho de massa', text:'Uma combinação focada em aporte proteico, força e maior densidade calórica.', categories:['Proteínas','Creatinas','Hipercalóricos'] },
    energia: { title:'Stack para energia e foco', text:'Seleção para treinos intensos, priorizando pré-treino e suporte à performance.', categories:['Pré-treinos','Creatinas','Snacks'] },
    recuperacao: { title:'Stack para recuperação', text:'Produtos para complementar proteína, aminoácidos e rotina pós-treino.', categories:['Proteínas','Aminoácidos','Vitaminas'] },
    saude: { title:'Stack para saúde e rotina', text:'Opções práticas para complementar alimentação e consistência diária.', categories:['Vitaminas','Snacks','Proteínas'] }
  };
  const productVisual = p => p.image ? `<img src="${p.image}" alt="${p.name}">` : `<div class="mini-pack mini-pack--${p.pack||'orange'}"><small>${p.brand||'ALFA'}</small><b>${(p.name||'PRODUTO').split(' ')[0]}</b></div>`;

  function pickByGoal(goal){ const data=goalMap[goal]; if(!data)return []; const products=getStore().products||[]; return data.categories.map(cat=>products.filter(p=>p.stock>0&&p.category===cat).sort((a,b)=>(b.rating||0)-(a.rating||0))[0]).filter(Boolean).slice(0,3); }
  function showGoal(goal, scroll=false){ const data=goalMap[goal], picks=pickByGoal(goal), box=$('#smartResult'); if(!data||!box)return; $$('.goal-card').forEach(x=>x.classList.toggle('active',x.dataset.goal===goal)); $('#smartResultTitle').textContent=data.title; $('#smartResultText').textContent=data.text; $('#smartResultProducts').innerHTML=picks.map(p=>`<button class="smart-product" data-product-id="${p.id}">${productVisual(p)}<span><b>${p.name}</b><small>${p.category}</small><strong>${moneyV5(p.price)}</strong></span></button>`).join(''); box.hidden=false; box.dataset.goal=goal; if(scroll) box.scrollIntoView({behavior:'smooth',block:'center'}); }

  function renderCompareTray(){ const store=getStore(), ids=[...compare], slots=$('#compareSlots'), btn=$('#openCompare'); if(!slots)return; slots.innerHTML=ids.map(id=>{const p=store.products.find(x=>x.id===id);return p?`<div class="compare-chip">${productVisual(p)}<span><b>${p.name}</b><small>${moneyV5(p.price)}</small></span><button data-remove-compare="${p.id}"><i class="fa-solid fa-xmark"></i></button></div>`:''}).join(''); $('.compare-empty').style.display=ids.length?'none':'flex'; btn.disabled=ids.length<2; }
  function toggleCompare(id){ if(compare.has(id)) compare.delete(id); else { if(compare.size>=3){window.toast?.('Você pode comparar até 3 produtos','fa-code-compare'); return;} compare.add(id); } renderCompareTray(); syncCompareButtons(); }
  function syncCompareButtons(){ $$('[data-compare-id]').forEach(b=>b.classList.toggle('active',compare.has(Number(b.dataset.compareId)))); }
  function injectCompareButtons(){ $$('.product-card').forEach(card=>{if(card.querySelector('[data-compare-id]'))return; const id=Number(card.dataset.card || card.querySelector('[data-product-id]')?.dataset.productId || card.dataset.id || card.querySelector('[onclick*="openProduct"]')?.getAttribute('onclick')?.match(/\d+/)?.[0]); if(!id)return; const media=card.querySelector('.product-card__media')||card; const b=document.createElement('button');b.className='compare-button';b.dataset.compareId=id;b.innerHTML='<i class="fa-solid fa-code-compare"></i><span>Comparar</span>';media.appendChild(b);}); syncCompareButtons(); }
  function openCompareModal(){ const store=getStore(), ids=[...compare], products=ids.map(id=>store.products.find(p=>p.id===id)).filter(Boolean); if(products.length<2)return; const rows=[['Produto',p=>`<div class="compare-product-head">${productVisual(p)}<b>${p.name}</b></div>`],['Preço',p=>`<strong class="compare-price">${moneyV5(p.price)}</strong>`],['Categoria',p=>p.category],['Avaliação',p=>`<span class="stars">★ ${p.rating||0}</span>`],['Estoque',p=>p.stock>0?`${p.stock} unidades`:'Esgotado'],['Marca',p=>p.brand||'—'],['Destaque',p=>p.bestseller?'Mais vendido':p.launch?'Lançamento':p.badge||'—']]; $('#compareTable').innerHTML=`<table><tbody>${rows.map(([label,fn])=>`<tr><th>${label}</th>${products.map(p=>`<td>${fn(p)}</td>`).join('')}</tr>`).join('')}</tbody></table>`; $('#compareModal').classList.add('open');document.body.classList.add('no-scroll'); }
  const closeCompare=()=>{$('#compareModal')?.classList.remove('open');document.body.classList.remove('no-scroll')};

  function initKit(){ const store=getStore(), products=store.products.filter(p=>p.stock>0); const fill=(sel,cats)=>{const el=$(sel); if(!el)return; const list=products.filter(p=>cats.includes(p.category)); el.innerHTML='<option value="">Escolha...</option>'+list.map(p=>`<option value="${p.id}">${p.name} — ${moneyV5(p.price)}</option>`).join('');}; fill('#kitBase',['Proteínas','Hipercalóricos']);fill('#kitBoost',['Creatinas','Pré-treinos']);fill('#kitExtra',['Vitaminas','Aminoácidos','Snacks']); updateKit(); }
  function kitProducts(){ const store=getStore(); return ['#kitBase','#kitBoost','#kitExtra'].map(s=>Number($(s)?.value)).filter(Boolean).map(id=>store.products.find(p=>p.id===id)).filter(Boolean); }
  function updateKit(){ const ps=kitProducts(), old=ps.reduce((a,p)=>a+Number(p.price||0),0), discounted=old*.92; $('#kitOldTotal').textContent=moneyV5(old);$('#kitTotal').textContent=moneyV5(discounted); }
  function addKit(){ const ps=kitProducts(); if(ps.length<2){window.toast?.('Escolha pelo menos 2 itens para montar o kit','fa-boxes-stacked');return;} ps.forEach(p=>window.addToCart?.(p.id,p.flavors?.[0]||'Padrão',p.sizes?.[0]||'Único',1,p.price*.92,'custom-kit')); window.toast?.('Kit personalizado adicionado com 8% OFF','fa-boxes-stacked'); }

  function initCountdown(){ const key='alfa_v5_flash_end'; let end=Number(localStorage.getItem(key)); if(!end||end<Date.now()){end=Date.now()+24*60*60*1000;localStorage.setItem(key,end)} const tick=()=>{let d=Math.max(0,end-Date.now()),h=Math.floor(d/3600000),m=Math.floor(d%3600000/60000),s=Math.floor(d%60000/1000); if($('#cdHours'))$('#cdHours').textContent=String(h).padStart(2,'0');if($('#cdMinutes'))$('#cdMinutes').textContent=String(m).padStart(2,'0');if($('#cdSeconds'))$('#cdSeconds').textContent=String(s).padStart(2,'0');};tick();setInterval(tick,1000); }

  function initMega(){ const trigger=$('#megaMenuTrigger'), menu=$('#megaMenu'); if(!trigger||!menu)return; const close=()=>{menu.classList.remove('open');menu.setAttribute('aria-hidden','true')}; trigger.onclick=e=>{e.stopPropagation();menu.classList.toggle('open');menu.setAttribute('aria-hidden',menu.classList.contains('open')?'false':'true')}; document.addEventListener('click',e=>{if(!menu.contains(e.target)&&e.target!==trigger)close()}); $$('[data-mega-filter]').forEach(a=>a.onclick=()=>{const target=$$('[data-filter]').find(b=>b.dataset.filter===a.dataset.megaFilter); if(target) target.click(); close()}); $$('[data-goal]',menu).forEach(b=>b.onclick=()=>{showGoal(b.dataset.goal,true);close()}); }

  let quiz={step:0,answers:{}};
  const questions=[{key:'goal',title:'Qual é seu objetivo principal?',options:[['massa','Ganhar massa'],['energia','Energia e foco'],['recuperacao','Recuperação'],['saude','Saúde e rotina']]},{key:'experience',title:'Como está sua rotina de treino?',options:[['inicio','Estou começando'],['regular','Treino com regularidade'],['intenso','Treino intenso']]},{key:'budget',title:'Qual faixa você prefere?',options:[['economico','Mais econômica'],['equilibrado','Melhor custo-benefício'],['premium','Quero opções premium']]}];
  function renderQuiz(){ const q=questions[quiz.step], box=$('#quizContent'); $('#quizProgress').style.width=`${((quiz.step)/questions.length)*100}%`; if(!q){ const picks=pickByGoal(quiz.answers.goal); $('#quizProgress').style.width='100%'; box.innerHTML=`<div class="quiz-result"><i class="fa-solid fa-bolt"></i><h3>Seu Stack Alfa está pronto.</h3><p>Selecionamos ${picks.length} produtos alinhados ao seu objetivo. Você pode revisar antes de adicionar.</p><div>${picks.map(p=>`<div class="quiz-pick">${productVisual(p)}<span><b>${p.name}</b><small>${moneyV5(p.price)}</small></span></div>`).join('')}</div><button class="btn btn--primary" id="quizUseResult">VER MINHA SELEÇÃO</button></div>`; $('#quizUseResult').onclick=()=>{closeRecommender();showGoal(quiz.answers.goal,true)};return;} box.innerHTML=`<div class="quiz-step"><small>PASSO ${quiz.step+1} DE ${questions.length}</small><h3>${q.title}</h3><div class="quiz-options">${q.options.map(([v,l])=>`<button data-quiz-value="${v}"><i class="fa-solid fa-arrow-right"></i>${l}</button>`).join('')}</div></div>`; $$('[data-quiz-value]',box).forEach(b=>b.onclick=()=>{quiz.answers[q.key]=b.dataset.quizValue;quiz.step++;renderQuiz()}); }
  function openRecommender(){quiz={step:0,answers:{}};renderQuiz();$('#recommenderModal').classList.add('open');document.body.classList.add('no-scroll')}
  function closeRecommender(){$('#recommenderModal')?.classList.remove('open');document.body.classList.remove('no-scroll')}

  function commandItems(){ const store=getStore(); return [{label:'Abrir carrinho',icon:'fa-cart-shopping',action:()=>window.openCart?.()},{label:'Smart Pick — descobrir meu stack',icon:'fa-bolt',action:openRecommender},{label:'Ver combos',icon:'fa-boxes-stacked',action:()=>$('#combos')?.scrollIntoView({behavior:'smooth'})},...store.products.map(p=>({label:p.name,sub:p.category,icon:'fa-cube',action:()=>window.openProduct?.(p.id)}))]; }
  function openCommand(){ $('#commandPalette').classList.add('open');document.body.classList.add('no-scroll');renderCommand('');setTimeout(()=>$('#commandInput').focus(),80)}
  function closeCommand(){ $('#commandPalette')?.classList.remove('open');document.body.classList.remove('no-scroll')}
  function renderCommand(q){ q=(q||'').toLowerCase(); const items=commandItems().filter(x=>(x.label+' '+(x.sub||'')).toLowerCase().includes(q)).slice(0,9); $('#commandResults').innerHTML=items.map((x,i)=>`<button data-command-index="${i}"><i class="fa-solid ${x.icon}"></i><span><b>${x.label}</b>${x.sub?`<small>${x.sub}</small>`:''}</span><i class="fa-solid fa-arrow-right"></i></button>`).join('')||'<p class="command-empty">Nenhum resultado.</p>'; $$('[data-command-index]').forEach((b,i)=>b.onclick=()=>{items[i].action();closeCommand()}); }

  function evolutionPhases(){ const sections=$$('[data-evolution-phase]'); const onScroll=()=>{let phase='origin'; const y=innerHeight*.48; sections.forEach(s=>{const r=s.getBoundingClientRect();if(r.top<y&&r.bottom>y)phase=s.dataset.evolutionPhase});document.documentElement.dataset.evolutionPhase=phase;};window.addEventListener('scroll',onScroll,{passive:true});onScroll(); }

  function bind(){ document.addEventListener('click',e=>{const c=e.target.closest('[data-compare-id]');if(c){e.preventDefault();e.stopPropagation();toggleCompare(Number(c.dataset.compareId))} const r=e.target.closest('[data-remove-compare]');if(r){toggleCompare(Number(r.dataset.removeCompare))}}); $$('.goal-card').forEach(b=>b.onclick=()=>showGoal(b.dataset.goal,true)); $('#addSmartStack').onclick=()=>{const picks=pickByGoal($('#smartResult').dataset.goal);picks.forEach(p=>window.addToCart?.(p.id,p.flavors?.[0]||'Padrão',p.sizes?.[0]||'Único',1,p.price));window.toast?.('Stack inteligente adicionado','fa-bolt')}; ['#kitBase','#kitBoost','#kitExtra'].forEach(s=>$(s)?.addEventListener('change',updateKit));$('#addCustomKit').onclick=addKit;$('#openCompare').onclick=openCompareModal;$$('[data-close-compare]').forEach(x=>x.onclick=closeCompare);$$('[data-open-recommender]').forEach(x=>x.onclick=openRecommender);$$('[data-close-recommender]').forEach(x=>x.onclick=closeRecommender);$$('[data-close-command]').forEach(x=>x.onclick=closeCommand);$('#commandInput')?.addEventListener('input',e=>renderCommand(e.target.value));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape'){closeCommand();closeCompare();closeRecommender()}}); const obs=new MutationObserver(()=>injectCompareButtons()); const grid=$('#productGrid');if(grid)obs.observe(grid,{childList:true,subtree:true}); }

  function init(){ initMega();initKit();initCountdown();renderCompareTray();bind();injectCompareButtons();evolutionPhases(); const searchTrigger=$('#searchTrigger');if(searchTrigger)searchTrigger.title='Pesquisar • Ctrl+K para busca rápida'; }
  document.addEventListener('DOMContentLoaded',()=>setTimeout(init,50));
})();
