// ============================================================
// ALFA SUPLEMENTOS V9 — FIDELIDADE, INDICAÇÃO E ALERTAS
// ============================================================
(()=>{
'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const KEY='alfa_v9_growth';
const alertKey='alfa_v9_product_alerts';
const loadStore=()=>window.AlfaStore?.load?.()||window.STORE||window.ALFA_DEFAULT_DATA||{};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const phoneDigits=v=>(v||'').replace(/\D/g,'');
function growth(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function saveGrowth(v){localStorage.setItem(KEY,JSON.stringify(v))}
function alerts(){try{return JSON.parse(localStorage.getItem(alertKey)||'[]')}catch{return []}}
function saveAlerts(v){localStorage.setItem(alertKey,JSON.stringify(v))}
function toast(msg){if(typeof window.toast==='function') return window.toast(msg,'fa-bolt'); const el=document.createElement('div');el.textContent=msg;Object.assign(el.style,{position:'fixed',right:'18px',top:'100px',zIndex:10010,background:'#ff6a00',color:'#111',padding:'12px 16px',borderRadius:'12px',fontWeight:'800'});document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
function customerByPhone(phone){const d=loadStore(),p=phoneDigits(phone);return (d.customers||[]).find(c=>phoneDigits(c.phone)===p)}
function completedSpend(phone){const d=loadStore(),p=phoneDigits(phone);return (d.orders||[]).filter(o=>phoneDigits(o.customer?.phone||o.phone)===p && o.status==='completed').reduce((s,o)=>s+Number(o.total||0),0)}
function profile(phone){const d=loadStore(),s=d.settings||{},customer=customerByPhone(phone),spent=Math.max(Number(customer?.totalSpent||0),completedSpend(phone));const rate=Number(s.loyaltyPointsPerReal||1),points=Math.floor(spent*rate),pro=Number(s.loyaltyProThreshold||500),elite=Number(s.loyaltyEliteThreshold||1500);let level='START',next=pro;if(spent>=elite){level='ELITE';next=null}else if(spent>=pro){level='PRO';next=elite}return {customer,spent,points,level,next};}
function renderProfile(p){$('#v9LevelName')&&($('#v9LevelName').textContent=p.level);if($('#v9PointsHeadline'))$('#v9PointsHeadline').textContent=p.customer?`${p.points} pontos Alfa • ${p.level}`:'Cliente ainda não encontrado';if($('#v9PointsText'))$('#v9PointsText').textContent=p.customer?(p.next?`${money(p.next-p.spent)} em compras concluídas para o próximo nível.`:`Você chegou ao nível máximo atual do Clube Alfa.`):'Confira o número usado nas compras concluídas pelo WhatsApp.';saveGrowth({...growth(),phone:p.customer?.phone||'',lastProfile:p});}
function referralCode(phone){const p=phoneDigits(phone);if(!p)return null;let hash=0;for(const ch of p)hash=(hash*31+Number(ch))%99999;return `ALFA${String(hash).padStart(5,'0')}`}
function setupLoyalty(){const form=$('#v9LoyaltyLookup');if(!form)return;const saved=growth();if(saved.phone)$('#v9LoyaltyPhone').value=saved.phone;form.addEventListener('submit',e=>{e.preventDefault();const phone=$('#v9LoyaltyPhone').value,p=profile(phone);renderProfile(p)});$('#v9ReferralButton')?.addEventListener('click',async()=>{const phone=$('#v9LoyaltyPhone')?.value||saved.phone||'';const code=referralCode(phone);if(!code)return toast('Digite seu WhatsApp para gerar o código');try{await navigator.clipboard.writeText(code);toast(`Código ${code} copiado`)}catch{prompt('Seu código de indicação:',code)}});}
function toggleAlert(id,type='stock'){let list=alerts();const key=`${id}:${type}`;const exists=list.some(x=>x.key===key);if(exists)list=list.filter(x=>x.key!==key);else list.push({key,id:Number(id),type,createdAt:new Date().toISOString()});saveAlerts(list);decorateCards();toast(exists?'Alerta removido':'Alerta salvo neste dispositivo')}
function decorateCards(){const list=alerts();$$('.product-card[data-card]').forEach(card=>{const id=Number(card.dataset.card);if(card.querySelector('.v9-alert-chip'))return;const b=document.createElement('button');b.className='v9-alert-chip'+(list.some(x=>x.id===id)?' active':'');b.innerHTML='<i class="fa-regular fa-bell"></i> ALERTA';b.title='Salvar alerta de reposição/preço';b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleAlert(id,'watch')};const media=card.querySelector('.product-card__media')||card;b.style.position='absolute';media.appendChild(b)});$$('.v9-alert-chip').forEach(b=>{const card=b.closest('[data-card]');if(card)b.classList.toggle('active',list.some(x=>x.id===Number(card.dataset.card)))})}
function alertPanel(){let panel=$('#v9AlertPanel');if(panel)return panel;panel=document.createElement('div');panel.id='v9AlertPanel';panel.className='v9-alert-panel';panel.innerHTML='<div class="v9-alert-box"><button class="v9-close" aria-label="Fechar">×</button><span class="eyebrow"><span></span> ALERTAS V9</span><h3>Produtos monitorados</h3><p style="color:#888">Os alertas ficam salvos neste dispositivo. Quando a loja estiver conectada a automações externas, esta lista poderá alimentar notificações reais.</p><div class="v9-alert-list" id="v9AlertList"></div></div>';document.body.appendChild(panel);panel.addEventListener('click',e=>{if(e.target===panel||e.target.closest('.v9-close'))panel.classList.remove('open')});return panel}
function openAlerts(){const panel=alertPanel(),d=loadStore(),list=alerts();$('#v9AlertList',panel).innerHTML=list.length?list.map(a=>{const p=(d.products||[]).find(x=>Number(x.id)===Number(a.id));return `<article><span><b>${p?.name||'Produto'}</b><small>${p?.stock>0?'Em estoque':'Sem estoque'} • ${p?money(p.price):''}</small></span><button data-v9-remove="${a.key}" aria-label="Remover"><i class="fa-solid fa-trash"></i></button></article>`}).join(''):'<div style="padding:25px;color:#777;text-align:center">Nenhum alerta salvo.</div>';$$('[data-v9-remove]',panel).forEach(b=>b.onclick=()=>{saveAlerts(alerts().filter(x=>x.key!==b.dataset.v9Remove));openAlerts();decorateCards()});panel.classList.add('open')}
function observeProducts(){decorateCards();const grid=$('#productGrid');if(grid)new MutationObserver(()=>decorateCards()).observe(grid,{childList:true,subtree:true});$('#v9OpenAlerts')?.addEventListener('click',openAlerts)}
function accountTab(){const tabs=$('.v8-account-tabs');if(!tabs||tabs.querySelector('[data-v9-account-tab]'))return;const b=document.createElement('button');b.dataset.v9AccountTab='club';b.innerHTML='<i class="fa-solid fa-crown"></i> Clube Alfa';tabs.appendChild(b);b.onclick=()=>{$$('.v8-account-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const content=$('#v8AccountContent');const saved=growth(),p=saved.phone?profile(saved.phone):null;content.innerHTML=`<div class="v8-track-box"><div><span>CLUBE ALFA V9</span><h3>${p?.customer?`${p.points} pontos • ${p.level}`:'Consulte seu perfil na seção Clube Alfa'}</h3><p>${p?.customer?`Total considerado: ${money(p.spent)}.`:'Use o mesmo WhatsApp informado em seus pedidos.'}</p></div><button class="btn btn--primary" onclick="document.querySelector('#v8Account').setAttribute('aria-hidden','true');document.querySelector('#clube-alfa').scrollIntoView({behavior:'smooth'})">ABRIR CLUBE ALFA</button></div>`}}
function init(){setupLoyalty();observeProducts();accountTab();const saved=growth();if(saved.phone)renderProfile(profile(saved.phone));document.documentElement.dataset.v9='ready'}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
